name: Build Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      # Setup Node environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Lint, format & tests
        run: |
          pnpm lint
          pnpm format --check
          pnpm test:unit

      - name: Build and push Docker image
        run: |
          docker build -t fethca/movie-scrapper:latest .
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
          docker push fethca/movie-scrapper:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy new image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ "$(docker ps -q --filter "name=movie-scrapper")" ]; then docker stop movie-scrapper && docker rm movie-scrapper; fi
            if [ "$(docker images -q 'fethca/movie-scrapper')" ]; then docker rmi fethca/movie-scrapper; fi
            cd ~/traefik
            docker-compose up -d --remove-orphans movie-scrapper
